AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for MySQL RDS instance with multi-AZ, RDS Proxy, VPC, Subnets, and a Bastion Host with EIP.'

Parameters:
  DBName:
    Description: The database name
    Type: String

  DBUser:
    Description: The database admin account username
    Type: String

  DBPassword:
    Description: The password for the database admin account
    Type: String
    NoEcho: true

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the Bastion Host
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: '10.0.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: 'MyVPC'

  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: '10.0.1.0/24'
      Tags:
        - Key: Name
          Value: 'MySubnet1'

  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: '10.0.2.0/24'
      Tags:
        - Key: Name
          Value: 'MySubnet2'

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet1
      RouteTableId: !Ref PublicRouteTable

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RDS security group
      VpcId: !Ref VPC

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 security group
      VpcId: !Ref VPC

  MySQLRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: mysql
      MultiAZ: true
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      BackupRetentionPeriod: 7

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS instance
      SubnetIds:
        - !Ref Subnet1
        - !Ref Subnet2

  RDSProxy:
    Type: AWS::RDS::DBProxy
    Properties:
      DBProxyName: 'MyRDSProxy'
      EngineFamily: MYSQL
      RoleArn: !GetAtt RDSProxyRole.Arn
      VpcSecurityGroupIds:
        - !Ref RDSSecurityGroup
      VpcSubnetIds:
        - !Ref Subnet1
        - !Ref Subnet2
      Auth:
        - AuthScheme: SECRETS
          IAMAuth: DISABLED
          SecretArn: !Ref RDSSecret

  RDSProxyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - 'rds.amazonaws.com'
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole'

  RDSSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: 'RDSInstanceSecret'
      SecretString: !Sub '{"username":"${DBUser}", "password":"${DBPassword}"}'

  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SubnetId: !Ref Subnet1
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      ImageId: ami-0c55b159cbfafe1f0 # This is an Amazon Linux 2 LTS AMI ID; replace with the appropriate AMI ID for your region

  EIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref BastionHost

Outputs:
  VPCId:
    Description: The VPC ID
    Value: !Ref VPC

  Subnet1Id:
    Description: The Subnet1 ID
    Value: !Ref Subnet1

  Subnet2Id:
    Description: The Subnet2 ID
    Value: !Ref Subnet2

  RDSInstanceEndpoint:
    Description: The RDS instance endpoint
    Value: !GetAtt MySQLRDSInstance.Endpoint.Address

  RDSProxyEndpoint:
    Description: The RDS proxy endpoint
    Value: !GetAtt RDSProxy.Endpoint

  BastionHostPublicIP:
    Description: The Elastic IP address for the Bastion Host
    Value: !Ref EIP
